language: python

python: 3.6

cache:
  timeout: 1000
  directories:
    - $HOME/.stack/
    - $HOME/.ghcjs/
    - $HOME/.local/bin/
    - .stack-work/

before_install:
# Download and unpack the stack executable
    - sudo apt-get update && sudo apt-get install -y software-properties-common openssh-client libzmq3-dev rpm2cpio
    - sudo add-apt-repository -y ppa:hvr/ghc
    - sudo apt-get update
    - sudo apt-get install -y cabal-install-1.22 ghc-8.0.3
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=/opt/ghc/8.0.2/bin:$PATH
    - stack install hsc2hs
    - stack install happy
    - curl -o /tmp/luna-manager http://packages.luna-lang.org/linux/luna-manager
    - sudo mv /tmp/luna-manager /usr/bin
    - curl -o /tmp/packageConfig.yaml http://packages.luna-lang.org/linux/studio/packageConfig.yaml
    - sudo mv /tmp/packageConfig.yaml /home/travis/packageConfig.yaml
    - chmod +x /usr/bin/luna-manager

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2


install:
    - "npm install -g npm"
    - "pip install requests"

script:
    - stack build --stack-yaml=build/backend/stack.yaml --only-dependencies --install-ghc --test --fast -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - stack build --stack-yaml=luna-studio/stack.yaml --only-dependencies --install-ghc --fast -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - stack build --stack-yaml=runner/stack.yaml --only-dependencies --install-ghc --fast -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - stack build --stack-yaml build/backend/stack.yaml --copy-bins --no-run-tests --no-run-benchmarks -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - stack build --stack-yaml luna-studio/stack.yaml --fast -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - stack build --stack-yaml runner/stack.yaml --copy-bins --fast -j1 --ghc-options=-j1 --ghc-options="+RTS -M3G -RTS" +RTS -N1 -RTS
    - luna-manager make-package /home/travis/packageConfig.yaml -v
