---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become_user: root
  vars:
    home: '{{ lookup("env", "HOME")}}'
    luna_repo_path: 'ssh://git@github.com/luna/luna-manager'
    luna_dir: '{{ home }}/luna-develop'
    luna_tools_dir: '{{ luna_dir }}/tools'
    luna_apps_dir: '{{ luna_dir }}/apps'
    luna_libs_dir: '{{ luna_dir }}/libs'
    luna_manager_dir: '{{ luna_apps_dir }}/luna-manager'
    luna_studio_dir: '{{ luna_apps_dir }}/luna-studio'
    luna_manager_url: 'http://packages.luna-lang.org/linux/manager/luna-manager'
    pyenv_root: '{{ luna_tools_dir }}/python/pyenv'
    pyenv_bin: '{{ pyenv_root }}/bin/pyenv'
  environment:
    LD_LIBRARY_PATH: '{{ luna_libs_dir }}:{{ lookup("env", "LD_LIBRARY_PATH") }}'
    PYENV_ROOT: '{{ pyenv_root }}'

  tasks:
  - name: install apt packages
    become: true
    apt: name={{item}} state=present
    with_items:
      - wget
      - build-essential
      - libffi-dev
      - libgmp-dev
      - xz-utils
      - zlib1g-dev
      - git
      - gnupg
      - libzmq3-dev
      - libpng-dev
      - openssl
      - python-setuptools
      - libssl-dev
      - libtinfo-dev
      - pkg-config
      - alex

  - name: install pip
    become: true
    easy_install:
      name: pip
      state: latest

  - name: download luna manager
    get_url:
      url: '{{ luna_manager_url }}'
      dest: '{{ home }}'
      mode: 0777

  - name: run luna manager to download LS
    command: ./luna-manager develop luna-studio --verbose

  - name: clone luna manager
    git:
      repo: '{{ luna_repo_path }}'
      dest: '{{ luna_manager_dir }}'
      clone: yes

  - name: ensure execute permissions on luna-shell.sh
    file:
      path: '{{ luna_studio_dir }}/luna-shell.sh'
      mode: 0777

  - name: set python version with pyenv
    command: "{{ pyenv_bin }} local 3.6.2"

  - name: build luna manager
    shell: 'source {{ luna_studio_dir }}/luna-shell.sh && stack install'
    args:
      executable: /bin/bash
      chdir: '{{ luna_manager_dir }}'

